version: "3"

services:
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  wkhtmltopdf:
    container_name: wkhtmltopdf-aas
    image: "openlabs/docker-wkhtmltopdf-aas"
    ports:
      - "4133:80"
    restart: unless-stopped
#    depends_on:
#      - postgres
    volumes:
      - .:/data
